### ISSUE TITLE
[Bug] Trip overlay disappears when switching inventory tabs

### ISSUE THREAD

**Issue by CreativeTechGuy** [MosheBenZacharia/GP-Per-Hour#2]
Whenever you switch to another tab that isn't the inventory, the trip overlay disappears. I cannot seem to find if any of the settings affect this.

I'm reporting this as a bug because it was surprising/unexpected. But I suspect it was intentionally coded this way. Is there a reason it needs to be only when the inventory is visible? It's very jarring for it to constantly appear and disappear as you switch tabs.

**Comment by MosheBenZacharia** [comment]
This is a relic of how the original overlay worked in the plugin I forked this from, but that was since ([partially](https://github.com/erversteeg/inventorytotal/issues/2)) fixed.

I agree it would be nice to have an option for it be always on screen. How would you imagine this would work? Would it only appear if you had some tab open in the bottom right and hide if nothing was open? Or would it always be on screen regardless?

**Comment by CreativeTechGuy** [comment]
It'd be nice if the overlay worked like all of the other RuneLite overlays where you could Alt+Drag it around and just place it somewhere or snap it relative to something else. I'm not sure about how it'd work in Resizable mode when everything is closed. I always play fixed so I didn't think about closing everything. When in doubt, add an option! 😛

**Comment by MosheBenZacharia** [comment]
Sounds good, I'll keep thinking about it!

**Comment by MosheBenZacharia** [comment]
Added an option to always show the trip overlay here: https://github.com/MosheBenZacharia/GP-Per-Hour/commit/cc55d0185bf20ad35440c71ec8448b8b5a1f1415

The easiest thing to do was just cache the previous location of the inventory widget, so hopefully that is good enough for now :) 

I'll close this issue when it merges into the plugin hub.

**Comment by MosheBenZacharia** [comment]
merged in https://github.com/runelite/plugin-hub/pull/4997 . restart runelite to receive the update :)
